# Generated by Django 4.0.1 on 2022-01-09 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryTitle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.TextField()),
                ('QuestionType', models.TextField()),
                ('questionScore', models.IntegerField()),
                ('QuestionNist', models.TextField()),
                ('Category_id', models.ForeignKey(db_column='Category', on_delete=django.db.models.deletion.CASCADE, related_name='Category_id', to='Audit.category')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnswerInput', models.TextField()),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Audit.question')),
                ('userLink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
