# Generated by Django 4.0.1 on 2022-01-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Category_id',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='category',
            name='CategoryTitle',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='question',
            name='QuestionNist',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='QuestionType',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionText',
            field=models.CharField(max_length=50),
        ),
    ]
