# Generated by Django 4.0.1 on 2022-01-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0002_rename_category_id_question_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ScoreValue',
            field=models.TextField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='QuestionType',
            field=models.CharField(choices=[('YesNo', 'Yes Or No'), ('YesNoContent', 'Yes Or No + Content'), ('Content', 'Content Only')], max_length=20),
        ),
    ]
