# Generated by Django 4.0.1 on 2022-02-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0003_answer_scorevalue_alter_question_questiontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='ScoreValue',
        ),
    ]
